name: toolbox
description: A new flutter plugin project.
version: 0.0.1
author:
homepage:

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.3
  flutter_svg: ^0.22.0
  qr_flutter: ^4.0.0
  dio: ^4.0.0
  cookie_jar: ^3.0.1
  dio_cookie_manager: 2.0.0
  flutter_easyloading: 3.0.0
  # Toast插件 https://pub.flutter-io.cn/packages/fluttertoast/versions/6.0.1
  fluttertoast: ^8.0.7
  # Flutter 常用工具类库 https://github.com/Sky24n/flustars
  flustars: ^2.0.1
  # 格式化String https://github.com/Naddiseo/dart-sprintf
  sprintf: ^6.0.0
  event_bus: ^2.0.0
  nuid: ^2.1.0
  url_launcher: ^6.0.6
  flutter_image_compress: ^1.0.0
  image_picker: ^0.8.0+3
  image_cropper: ^1.4.0
  permission_handler: ^8.0.1
  pull_to_refresh: ^2.0.0
  flutter_webview_plugin: ^0.4.0
  photo_view: ^0.11.1
  audioplayers: ^0.19.0
  package_info: ^2.0.2
  # 微信，支付宝支付插件
  fluwx: ^3.4.2
  tobias: ^2.1.0
  flutter_logan: ^1.0.2
  intl: ^0.17.0
  flutter_bugly: ^0.3.2+1
  tencent_im_plugin: ^2.0.2

  fish_redux: ^0.3.7
  flutter_banner_swiper: ^0.1.4
  bottom_navigation_badge: ^1.0.3
  #  flutter_cupertino_date_picker: ^1.0.26+2
  # 解决flutter 1.20.0+移除了DiagnosticableMixin，导致flutter_cupertino_date_picker插件报错：Type 'DiagnosticableMixin' not found.
  flutter_cupertino_date_picker_fork: ^1.0.1
  photo_manager: ^0.4.8
  photo: ^0.4.8
  jpush_flutter:
    git:
      url: https://github.com/hacjy/jpush-flutter-plugin.git
      ref: master

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  # This section identifies this Flutter project as a plugin project.
  # The androidPackage and pluginClass identifiers should not ordinarily
  # be modified. They are used by the tooling to maintain consistency when
  # adding or updating assets for this project.
  plugin:
    androidPackage: com.ylzbtech.flutter.toolbox
    pluginClass: ToolboxPlugin

  assets:
    - assets/data/
    - assets/images/
  # To add assets to your plugin package, add an assets section, like this:
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg
  #
  # For details regarding assets in packages, see
  # https://flutter.dev/assets-and-images/#from-packages
  #
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # To add custom fonts to your plugin package, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts in packages, see
  # https://flutter.dev/custom-fonts/#from-packages
